services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: smolhog_analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./migrations:/docker-entrypoint-initdb.d/

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  postgres_data: