services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: smolhog_analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - smolhog-network

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smolhog-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - smolhog-network

  event-processor:
    build: 
      context: ./infra/backend/event-processor
    ports:
      - "8000:8000"
    volumes:
      - ./infra/backend/event-processor:/app
      - /app/venv
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - smolhog-network

  worker:
    build: 
      context: ./infra/backend/workers
    volumes:
      - ./infra/backend/workers:/app
      - /app/venv
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - smolhog-network

  dashboard:
    build: 
      context: ./infra/frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./infra/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://event-processor:8000
      - NODE_ENV=development
    depends_on:
      - event-processor
    networks:
      - smolhog-network

volumes:
  postgres_data:

networks:
  smolhog-network:
    driver: bridge