services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: smolhog_analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - smolhog-network

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smolhog-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - smolhog-network

  event-processor:
    build: 
      context: ./infra/backend/event-processor
    ports:
      - "8000:8000"
    volumes:
      - ./infra/backend/event-processor:/app
      - /app/venv
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - smolhog-network

  worker:
    build: 
      context: ./infra/backend/workers
    volumes:
      - ./infra/backend/workers:/app
      - /app/venv
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - smolhog-network

  dashboard:
    build: 
      context: ./infra/frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./infra/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://event-processor:8000
      - NODE_ENV=development
    depends_on:
      - event-processor
    networks:
      - smolhog-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infra/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    networks:
      - smolhog-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./infra/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - smolhog-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" 
      - "14268:14268" 
      - "4317:4317"   
      - "4318:4318"   
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - smolhog-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - smolhog-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"  
    volumes:
      - ./infra/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./infra/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./infra/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana  
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    depends_on:
      - loki
      - jaeger
      - prometheus
    networks:
      - smolhog-network

volumes:
  postgres_data:
  loki_data:
  prometheus_data:
  grafana_data:

networks:
  smolhog-network:
    driver: bridge